### ISSUE TITLE
Bug - "Submit Feedback" link does work

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#1448]
# Description
This bug was submitted by a user: The “provide Feedback” link doesn’t work. I had to right-click “copy email address” and paste it into outlook to get it to work.

# Steps to Reproduce
I tried to reproduce the bug on both IE and Chrome, on both the applicant and the manager portal, but it auto-generated an empty email for me after I clicked the link.

# Images
Place image attachments here.

- [ ] Regression test written.

**Comment by Khristophor** [comment]
@rositak this is usually due to not specifying a default email client on the user's computer/browser. Email can be handled in a multitude of ways (browser based: gmail, outlook, etc. or desktop applicant based: outlook, mail, etc). There also seems to be many users reporting this problem on Windows 10 before a "default" option is set through the operating system.

**Comment by rositak** [comment]
@Khristophor thanks for the comment. From the user's perspective, would it be possible to generate an error message letting them know that their computer/browser is not set up for that? I believe that'll help ease the anxiety.
