### ISSUE TITLE
Admin Portal

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#232]
# Description
An admin portal for talent cloud concierge service. 

Immediate use cases:
- Review and publish a job poster put together by a hiring manager. (publish functionality should be removed from the manager portal)
- Upgrade account to hiring manager
- Add new skills to the skills list (this has a higher degree of uncertainty) see #532

**Comment by Khristophor** [comment]
@tristan-orourke @joshdrink @gobyrne @xander-miller 
I think this is in a good spot. As I mentioned before I can't open a PR because it kills Github.

To test this out, check out the `feature/backpack` branch locally, run `composer install`, `php artisan migrate`, set up an admin user, and run the above SQL command in Postgres (Josh I think you're safe since you're on MySQL).

The admin portal lives at `/admin` (no localization), once you're in the dashboard has everything I've exposed for view/create/edit. If you think any other things should be available/reorganized/moved let me know.

Docs [for backpack are here](https://backpackforlaravel.com/docs/3.5/)
Almost all the functionality is under `app/Http/Controllers/Admin`.

Good luck, have fun.
