### ISSUE TITLE
Admin - Security SI-10 - Information Input Validation

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#271]
# Description
handling user input information

(A)        The information system checks the validity of [Assignment: organization-defined information inputs].

# Required for Completion
- [ ] Documentation

**Comment by gobyrne** [comment]
Tristan, can you please document (either here or link to it from here) our approach to user input validation. This should include discussion of how we are protected again SQL injection and other common security vulnerabilities.

Please address how we ensure Twitter & LinkedIn links are not actually sending people to somewhere malicious. Obviously, most of this needs to be on the server side so that security is insured.

**Comment by gobyrne** [comment]
We should also discuss where security vulnerabilities remain. Most notably we collect Links (which could link to anything) and as part of our workflow, Talent Cloud team members are supposed to open them.

**Comment by gobyrne** [comment]
Look into best practices for sanitization and acceptance of URLs.

**Comment by gobyrne** [comment]
Francois to look into accepting URLs
