### ISSUE TITLE
Applicant - UI for My Timeline step of new Application

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#2858]
# Description
Create the display components in React based on the mockups.

The Experience form modals should be completed as a separate task.

Can be done in Storybook with mock data.

# Images
https://xd.adobe.com/view/4ac43ee7-a919-4397-6888-ce98019603f7-3cf5/screen/5e2d2165-3b00-48aa-94e9-1f77b8dbb7fe/Step-2B-Requirements-15

**Comment by gobyrne** [comment]
For the forms, all dates should give error messages if they are in the past. @joshdrink can we even do that if there's no guarantee we can parse the date? If parse fails maybe we could give "invalid date format"?

To order the experience items: use Reverse Chronological order based on the End Date. "I'm currently active in this role" would ideally count as "today's date" which (in theory) would be the latest date possible.

**If it's relatively easy**
If the End Date is the same (whether because they are currently active or not) then those dates should be sub-sorted based on the start date. Once again in Reverse chronological. 

**Example of reverse chronological:**
- Start: January, 2015 | End: Ongoing
- Start: August, 2013 | End: Ongoing
- Start: December, 2015 | End: June, 2018
- Start: Jan, 1980 | End: May, 2015

-
