### ISSUE TITLE
Feature - Admin - Content Management

### ISSUE THREAD

**Issue by JoshBeveridge** [GCTC-NTGC/TalentCloud#2897]
# Description

**Is your feature request related to a problem? Please describe.**
Right now content changes/entry is extremely slow and cumbersome because it requires us to push new code changes to our production environment. This means that they generally get dictated by our feature releases, which inhibits our ability to make quick, efficient changes to enhance or test alternative content.

**Describe the solution you'd like**
Ideally it would be very useful for the project team to be able to manage content independently from the codebase. The ability to test, alter, improve copy that exists on the UI right now would be helpful for them, but also alleviate some of the asks on the dev team to modify the lang files as they are now. Content management/entry could totally skip the dev team.

Considerations:
- translation
- maybe we implement the CMS for only new features, and then retrofit existing pages/tools at a later date
- server configuration

**Describe alternatives you've considered**
After some quick discussion, there are React based CMS implementations that might be possible.
- https://strapi.io/

**Comment by Khristophor** [comment]
So from a dev perspective, options would be:

### Homebrew something ourselves in Laravel and/or React
This would give us the most flexibility but would be the most awful in terms of effort and maintenance. Not recommended unless we really can't find another useful solution.

### Use a Laravel-based solution
Something like [Twill](https://twill.io/) looks like it could fit our use case pretty well. Upside being we could maintain the benefits of the server side rendered pages (Twig). Downside being since we aren't server side rendering the bulk of our React pages we'd either need to query the information during the bundle generation or add more API routes that the frontend will have to hit to populate the pages on the client side.

### Use a headless solution
As Josh mentioned, [Strapi](https://strapi.io/) or [Cosmic](https://www.cosmicjs.com/knowledge-base/react-cms) look like interesting solutions, but we first will need to know if we can host these alongside our app on a subdomain or another url entirely. The major downside of headless is waiting for both written copy _and_ data to load from API requests on the client side, potentially drastically reducing user experience of the site. We would also need to adopt loading states for the entire page like [skeleton loading states](https://github.com/dvtng/react-loading-skeleton#readme) unless we can figure out a way to populate written copy during bundle generation.

**Comment by gobyrne** [comment]
@Khristophor was this a spike?
