### ISSUE TITLE
Spike - Data analytics for new Applications

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2942]
# Description
Research analytics issues to determine how  to track time spent on steps of the job application.

# Images
Place image attachments here.

**Comment by Khristophor** [comment]
After doing some research, there's very little in terms of "out of the box" packages for this kind of thing. 

Most solutions revolve around sending information to a 3rd party (usually Google) from the front end (React), or consuming information from a 3rd party to the back end (Laravel).

The best way for us to get the information we're looking for is to just collect it ourselves and store it in our database, although this will also involve creating some visualizations for the data.

**Comment by Khristophor** [comment]
For example:

[NY Times created a custom tracking library](https://github.com/nytimes/react-tracking) but it expects to send the data off to GA or another provider, we might be able to use this and repurpose it, but it's likely overkill for our use case.

[This is a tutorial for a basic idle detection hook](https://egghead.io/lessons/react-detect-user-activity-with-a-custom-useidle-react-hook) so that we could get more accurate user interaction timings without much overhead.

[This is a Laravel package for retrieving analytics to be stored locally](https://github.com/spatie/laravel-analytics). We could look into how they set up the data storage on the Laravel side but it's likely overkill again.

**Comment by gobyrne** [comment]
Looks good, will come back to this when we're ready to use it.
