### ISSUE TITLE
Task - Add a banner that tells the user to switch browsers if using IE

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#4579]
# Description
Internet Explorer has serious performance issues and bugs. The easiest way to improve the experience of users using IE, is to tell them up front NOT to use IE.

This involves detecting which browser is using and conditionally displaying some kind of notification on every page. 

We still need designs on what the notification should look like.

**Comment by tristan-orourke** [comment]
@Jerryescandon Do you have an idea of what this should look like?

**Comment by bitliege** [comment]
@gobyrne Asked me to take a whirl at writing something for this:

"Hey! We noticed you're using Internet Explorer.

Thanks for visiting Talent Cloud! As [Microsoft has begun phasing out support in favor of Edge](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666), we recommend using Talent Cloud from a modern web browser for the best experience. We recommend looking at the following:

- [Microsoft Edge](https://www.microsoft.com/en-us/edge)
- [Apple Safari](https://www.apple.com/ca/safari/)
- [Google Chrome](https://www.google.ca/chrome/)
- [Mozilla Firefox](https://www.mozilla.org/en-CA/firefox/new/)

Can't access another browser? [Get in touch so we can learn more](mailto:talent.cloud-nuage.de.talents@tbs-sct.gc.ca)."

I recommend putting this content in a modal that opens on page load, particularly if we're going to stop worrying about IE, because eventually the experience won't function.

**Comment by tristan-orourke** [comment]
@bitliege If we make it a modal, when should it be shown? We could include it on every page, but only show it once per user (tracking that with a cookie, probably). We could show it every n days by making the cookie expire, or show it once browser session by having the cookie only last until the browser closes. We could do something like show it on every visit, but only on the home page.

**Comment by Jerryescandon** [comment]
I like that the modal gives a lot of info, in addition I would pair this modal with a banner right at the top. So that we can show the modal once, and then have a consistent banner across all pages.

**Comment by bitliege** [comment]
@tristan-orourke 
- I'd show it right on page load of any page
- dismissing it with cookie retention is ideal
- every visit is probably overkill

@Jerryescandon 
- I agree with a banner
- we might want to include a message that says something like "Talent Cloud is phasing out support for Internet Explorer. If you find a bug, please report it here. Learn more."
- then "Learn more." can trigger the modal again.

**Comment by gobyrne** [comment]
@bitliege are you taking a first pass at this?

**Comment by bitliege** [comment]
@gobyrne It's on my to-do list, yeah.
