### ISSUE TITLE
Bug - Reset Password email not sent

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/TalentCloud#5360]
# Description
No email is sent to reset a password when requested.

# Steps to Reproduce
1. Go to https://talent.canada.ca/en/password/reset
2. Enter in an email address of an existing user
3. Click Send Reset Password Link

**Comment by gggrant** [comment]
This issue was twofold:
- SendGrid account was not properly configured.
- Cron jobs for talentcloud and the reserve were conflicting.

Our SendGrid account and API keys have been updated, and mail has been stopped on the reserve. The issue appears to be resolved.

Still need to check before/after the next deployment to ensure our script is not causing issues with the queue, requiring a manual restart.
