### ISSUE TITLE
Applicant - Job cards read as several different links to different locations

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#613]
# Description
Placing other elements inside an <a> tag causes them to be read as separate links when reading the data with assistive technology.

Workaround for this without affecting the UI will require some investigation.

**Comment by joshdrink** [comment]
https://simplyaccessible.com/article/html5-block-links/

**Comment by joshdrink** [comment]
@gggrant Hmmm, now that I've read that article, I'm not sure we have much of a solution here. Apparently block links being read improperly is a legacy issue with how screen readers used to read XHTML, with the block link being perfectly valid HTML5. The author of that article basically summarizes their solution by saying that they just had to accept the variation in how screen readers read out block links, because it was better for something to be read out twice than not at all.

**Comment by gggrant** [comment]
@joshdrink Do you want to revisit this one yet?

**Comment by tristan-orourke** [comment]
Sounds like there's no solution, so I'm going to close this issue.
