### ISSUE TITLE
Applicant/Manager - Fix styling of labels with long text

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/TalentCloud#822]
![Screen Shot 2019-03-20 at 4 29 22 PM](https://user-images.githubusercontent.com/22059495/54720336-89471e00-4b35-11e9-8eda-2f0f38f74382.png)

Labels that are over one line, overflow out of the parent container.

**Comment by joshdrink** [comment]
Might want to consider holding on this for now - design system inputs solve this issue, and at the end of the day, a label this long should be reworded to be more concise anyway. Unfortunately fixing this in the existing input framework will be difficult, because the height of the input has not relationship with the length of the label, so we'd have to run JS to check to see if the length is too visually long, and it gets hairy.
